/**
  *@file ${proto.fileName}.cpp
  *@brief generated protocol source code
  *@author make_protocol.py
  *@date 03/18/19
  */

/***********************************************************
        THIS FILE IS AUTOGENERATED. DO NOT MODIFY
***********************************************************/

#include "${proto.fileName}.h"
#include <assert.h>


//Define packet IDs
% for packet in proto.packets:
#define ${} ${packet.globalName}_ID ${packet.packetId}
% endfor


//Global descriptors
% for packet in proto.packets:
poly_packet_desc_t* ${packet.globalName};
% endfor

% for field in proto.fields:
poly_field_desc_t* ${field.globalName};
% endfor

poly_service_t* ${proto.service()};

/*******************************************************************************
  Service Functions
*******************************************************************************/
/**
  *@brief attempts to process data in buffers and parse out packets
  */
void ${proto.prefix}_service_process()
{
  static ${proto.prefix}_packet_t metaPacket;
  static ${proto.prefix}_packet_t metaResponse;

  HandlerStatus_e status = PACKET_UNHANDLED;

  if(poly_service_try_parse(${proto.service()}, &metaPacket.mPacket) == PACKET_VALID)
  {

    //Dispatch packet
    switch(metaPacket.mPacket.mDesc->mTypeId)
    {
  % for packet in proto.packets:
      case ${packet.globalName}_ID:
      %if packet.hasResponse:
       poly_packet_init(&metaResponse.mPacket, ${packet.response.globalName},true);
       status = ${proto.prefix}_${packet.name.lower()}_handler(&metaPacket , &metaResponse );
      %else:
        poly_packet_init(&metaResponse.mPacket, ${proto.prefix.upper()}_ACK_PACKET, true);
        status = ${proto.prefix}_${packet.name.lower()}_handler(&metaPacket);
      %endif
        break;
  % endfor
      default:
        //we should never get here
        assert(false);
        break;
    }

    //If the packet was not handled, throw it to the default handler
    if(status == PACKET_UNHANDLED)
      status = ${proto.prefix}_default_handler(&metaPacket);

    //If we are inside this scope, then the poly_packet_t was allocated and needs to be destroyed
    poly_packet_destroy(&metaPacket.mPacket);
    poly_packet_destroy(&metaResponse.mPacket);
  }

}


/**
  *@brief initializes ${proto.prefix}_protocol
  *@param interfaceCount number of interfaces to create
  */
void ${proto.prefix}_service_init(int interfaceCount)
{

  ${proto.service()} = new_poly_service(${len(proto.packets)}, interfaceCount);

  //Build Packet Descriptors
% for packet in proto.packets:
  ${packet.globalName} = new_poly_packet_desc("${packet.name}", ${len(packet.fields)});
% endfor

  //Build Field Descriptors
% for field in proto.fields:
  ${field.globalName} = new_poly_field_desc("${field.name}", TYPE_${field.type.upper()}, ${field.arrayLen}, ${field.format.upper()});
% endfor

% for packet in proto.packets:
% if len(packet.fields) > 0:
  //Setting Field Descriptors for ${packet.name}
  % for field in packet.fields:
  poly_packet_desc_add_field(${packet.globalName} , ${field.globalName} , ${str(field.isRequired).lower()} );
  % endfor
% endif

% endfor

  //Register packet descriptors with the service
% for packet in proto.packets:
  poly_service_register_desc(${proto.service()}, ${packet.globalName});
% endfor

  poly_service_start(${proto.service()}, 512);

}


void ${proto.prefix}_service_register_tx( int iface, poly_tx_callback txCallBack)
{
  poly_service_register_tx_callback(${proto.service()}, iface,txCallBack);
}

void ${proto.prefix}_service_feed(int iface, uint8_t* data, int len)
{
  poly_service_feed(${proto.service()},iface,data,len);
}

HandlerStatus_e ${proto.prefix}_send(int iface, ${proto.prefix}_packet_t* metaPacket)
{
  return poly_service_send(${proto.service()}, iface, &metaPacket->mPacket);
}


/*******************************************************************************
  Meta packet
*******************************************************************************/

/**
  *@brief creates a new meta packet and returns a pointer to it
  *@param desc packet descriptor
  *@post creator is responsible for destroying with ${proto.prefix}_packet_destroy()
  *@return ptr to new meta packet
  */
${proto.prefix}_packet_t* new_${proto.prefix}_packet(poly_packet_desc_t* desc)
{
  ${proto.prefix}_packet_t* newMetaPacket = (${proto.prefix}_packet_t*) malloc(sizeof(${proto.prefix}_packet_t));

  //create new unallocated packet
  poly_packet_init(&newMetaPacket->mPacket, desc, true);

  return newMetaPacket;
}


/**
  *@brief frees memory allocated for metapacket
  *@param "metaPacket ptr to metaPacket
  */
void ${proto.prefix}_destroy(${proto.prefix}_packet_t* metaPacket)
{
  //free internal poly_packet_t
  poly_packet_destroy(&metaPacket->mPacket);

  //free memory
  free(metaPacket);
}

/*******************************************************************************

  Meta-Packet setters

*******************************************************************************/

% for field in proto.fields:
%if field.isArray:
void ${proto.prefix}_set${field.name.capitalize()}(${proto.prefix}_packet_t* packet, const ${field.getParamType()} val)
% else:
void ${proto.prefix}_set${field.name.capitalize()}(${proto.prefix}_packet_t* packet, ${field.getParamType()} val)
%endif
{
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, ${field.globalName});
%if field.isArray:
  poly_field_set(field,( const uint8_t*) val);
% else:
  poly_field_set(field,( const uint8_t*) &val);
% endif
}

% endfor

/*******************************************************************************
  Meta-Packet getters
*******************************************************************************/

% for field in proto.fields:
${field.getParamType()} ${proto.prefix}_get${field.name.capitalize()}(${proto.prefix}_packet_t* packet)
{
  ${field.getParamType()} val;
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, ${field.globalName});
%if field.isArray:
  val = (${field.getParamType()})poly_field_get(field, (uint8_t*)val);
% else:
  poly_field_get(field,(uint8_t*) &val);
% endif
  return val;
}

% endfor


/*******************************************************************************
  Weak packet handlers

  Do not modify these, just create your own without the '__weak' attribute
*******************************************************************************/
% for packet in proto.packets:
/**
  *@brief Handler for receiving ${packet.name.lower()} packets
  *@param packet ptr to ${packet.structName}  containing packet
  *@return handling status
  */
%if packet.hasResponse:
/*@brief Handler for ${packet.name} packets */
__attribute__((weak)) HandlerStatus_e ${proto.prefix}_${packet.name.lower()}_handler(${proto.prefix}_packet_t* ${packet.name}, ${proto.prefix}_packet_t* ${packet.response.name})
%else:
/*@brief Handler for ${packet.name} packets */
__attribute__((weak)) HandlerStatus_e ${proto.prefix}_${packet.name.lower()}_handler(${proto.prefix}_packet_t* ${packet.name})
%endif
{
  /* NOTE : This function should not be modified, when the callback is needed,
          ${proto.prefix}_${packet.name.lower()}_handler  should be implemented in the user file
  */
  return PACKET_UNHANDLED;
}
% endfor

/**
  *@brief catch-all handler for any packet not handled by its default handler
  *@param metaPacket ptr to ${proto.prefix}_packet_t containing packet
  *@return handling status
  */
__attribute__((weak)) HandlerStatus_e ${proto.prefix}_default_handler( ${proto.prefix}_packet_t * metaPacket)
{
  /* NOTE : This function should not be modified, when the callback is needed,
          ${proto.prefix}_default_handler  should be implemented in the user file
  */
  return PACKET_UNHANDLED;
}
