/**
  *@file SampleProtocol.cpp
  *@brief generated protocol source code
  *@author make_protocol.py
  *@date 03/18/19
  */

/***********************************************************
        THIS FILE IS AUTOGENERATED. DO NOT MODIFY
***********************************************************/

#include "SampleProtocol.h"

#include "Utilities/PolyPacket/poly_parser.h"


//Declare extern packet descriptors
poly_packet_desc_t* PP_ack;
poly_packet_desc_t* PP_SetData;
poly_packet_desc_t* PP_GetData;
poly_packet_desc_t* PP_RespData;
poly_packet_desc_t* PP_blockReq;
poly_packet_desc_t* PP_blockResp;


//Declare extern field descriptors
poly_field_desc_t* PF_src;
poly_field_desc_t* PF_dst;
poly_field_desc_t* PF_cmd;
poly_field_desc_t* PF_sensorA;
poly_field_desc_t* PF_sensorB;
poly_field_desc_t* PF_sensorName;
poly_field_desc_t* PF_blockOffset;
poly_field_desc_t* PF_blockSize;
poly_field_desc_t* PF_blockData;


poly_parser_t* SP_PARSER;

void sp_protocol_init()
{
  SP_PARSER = new_poly_parser(6,ifaces);

//Build Packet descriptors
  PP_ack = new_poly_packet_desc("ack", 0 );
  PP_SetData = new_poly_packet_desc("SetData", 5 );
  PP_GetData = new_poly_packet_desc("GetData", 5 );
  PP_RespData = new_poly_packet_desc("RespData", 5 );
  PP_blockReq = new_poly_packet_desc("blockReq", 4 );
  PP_blockResp = new_poly_packet_desc("blockResp", 5 );


  //Build Field descriptors
  PF_src = new_poly_field_desc("src", TYPE_UINT16 , 1 , FORMAT_HEX );
  PF_dst = new_poly_field_desc("dst", TYPE_UINT16 , 1 , FORMAT_HEX );
  PF_cmd = new_poly_field_desc("cmd", TYPE_UINT8 , 1 , FORMAT_HEX );
  PF_sensorA = new_poly_field_desc("sensorA", TYPE_INT16 , 1 , FORMAT_DEC );
  PF_sensorB = new_poly_field_desc("sensorB", TYPE_INT , 1 , FORMAT_DEC );
  PF_sensorName = new_poly_field_desc("sensorName", TYPE_STRING , 32 , FORMAT_ASCII );
  PF_blockOffset = new_poly_field_desc("blockOffset", TYPE_UINT32 , 1 , FORMAT_HEX );
  PF_blockSize = new_poly_field_desc("blockSize", TYPE_UINT32 , 1 , FORMAT_DEC );
  PF_blockData = new_poly_field_desc("blockData", TYPE_UINT8 , 64 , FORMAT_NONE );


  //Setting fields Descriptors for SetdataPacket
  poly_packet_desc_add_field(PP_SetData , PF_src , true );
  poly_packet_desc_add_field(PP_SetData , PF_dst , true );
  poly_packet_desc_add_field(PP_SetData , PF_sensorA , false );
  poly_packet_desc_add_field(PP_SetData , PF_sensorB , false );
  poly_packet_desc_add_field(PP_SetData , PF_sensorName , false );


  //Setting fields Descriptors for GetdataPacket
  poly_packet_desc_add_field(PP_GetData , PF_src , true );
  poly_packet_desc_add_field(PP_GetData , PF_dst , true );
  poly_packet_desc_add_field(PP_GetData , PF_sensorA , false );
  poly_packet_desc_add_field(PP_GetData , PF_sensorB , false );
  poly_packet_desc_add_field(PP_GetData , PF_sensorName , false );


  //Setting fields Descriptors for RespdataPacket
  poly_packet_desc_add_field(PP_RespData , PF_src , true );
  poly_packet_desc_add_field(PP_RespData , PF_dst , true );
  poly_packet_desc_add_field(PP_RespData , PF_sensorA , false );
  poly_packet_desc_add_field(PP_RespData , PF_sensorB , false );
  poly_packet_desc_add_field(PP_RespData , PF_sensorName , false );


  //Setting fields Descriptors for BlockreqPacket
  poly_packet_desc_add_field(PP_blockReq , PF_src , true );
  poly_packet_desc_add_field(PP_blockReq , PF_dst , true );
  poly_packet_desc_add_field(PP_blockReq , PF_blockOffset , true );
  poly_packet_desc_add_field(PP_blockReq , PF_blockSize , true );


  //Setting fields Descriptors for BlockrespPacket
  poly_packet_desc_add_field(PP_blockResp , PF_src , true );
  poly_packet_desc_add_field(PP_blockResp , PF_dst , true );
  poly_packet_desc_add_field(PP_blockResp , PF_blockOffset , true );
  poly_packet_desc_add_field(PP_blockResp , PF_blockSize , true );
  poly_packet_desc_add_field(PP_blockResp , PF_blockData , true );


  //Register packet descriptors with parser 
  poly_parser_register_desc(SP_PARSER,PP_ack);
  poly_parser_register_desc(SP_PARSER,PP_SetData);
  poly_parser_register_desc(SP_PARSER,PP_GetData);
  poly_parser_register_desc(SP_PARSER,PP_RespData);
  poly_parser_register_desc(SP_PARSER,PP_blockReq);
  poly_parser_register_desc(SP_PARSER,PP_blockResp);

 //Start parser
  poly_parser_start(SP_PARSER);

}

ack_packet_t* new_ack()
{
  ack_packet_t* newStruct = (ack_packet_t*) malloc(sizeof(ack_packet_t));
  newStruct->mPacket = new_poly_packet(PP_ack);

  newStruct->mPacket->mBound = true;

  return newStruct;
}

setdata_packet_t* new_setdata()
{
  setdata_packet_t* newStruct = (setdata_packet_t*) malloc(sizeof(setdata_packet_t));
  newStruct->mPacket = new_poly_packet(PP_SetData);

  poly_packet_gett_field(newStruct->mPacket, PF_src)->mData = (uint8_t*) &newStruct->src;
  poly_packet_gett_field(newStruct->mPacket, PF_dst)->mData = (uint8_t*) &newStruct->dst;
  poly_packet_gett_field(newStruct->mPacket, PF_sensorA)->mData = (uint8_t*) &newStruct->sensorA;
  poly_packet_gett_field(newStruct->mPacket, PF_sensorB)->mData = (uint8_t*) &newStruct->sensorB;
  poly_packet_gett_field(newStruct->mPacket, PF_sensorName)->mData = (uint8_t*) &newStruct->sensorName;
  newStruct->mPacket->mBound = true;

  return newStruct;
}

getdata_packet_t* new_getdata()
{
  getdata_packet_t* newStruct = (getdata_packet_t*) malloc(sizeof(getdata_packet_t));
  newStruct->mPacket = new_poly_packet(PP_GetData);

  poly_packet_gett_field(newStruct->mPacket, PF_src)->mData = (uint8_t*) &newStruct->src;
  poly_packet_gett_field(newStruct->mPacket, PF_dst)->mData = (uint8_t*) &newStruct->dst;
  poly_packet_gett_field(newStruct->mPacket, PF_sensorA)->mData = (uint8_t*) &newStruct->sensorA;
  poly_packet_gett_field(newStruct->mPacket, PF_sensorB)->mData = (uint8_t*) &newStruct->sensorB;
  poly_packet_gett_field(newStruct->mPacket, PF_sensorName)->mData = (uint8_t*) &newStruct->sensorName;
  newStruct->mPacket->mBound = true;

  return newStruct;
}

respdata_packet_t* new_respdata()
{
  respdata_packet_t* newStruct = (respdata_packet_t*) malloc(sizeof(respdata_packet_t));
  newStruct->mPacket = new_poly_packet(PP_RespData);

  poly_packet_gett_field(newStruct->mPacket, PF_src)->mData = (uint8_t*) &newStruct->src;
  poly_packet_gett_field(newStruct->mPacket, PF_dst)->mData = (uint8_t*) &newStruct->dst;
  poly_packet_gett_field(newStruct->mPacket, PF_sensorA)->mData = (uint8_t*) &newStruct->sensorA;
  poly_packet_gett_field(newStruct->mPacket, PF_sensorB)->mData = (uint8_t*) &newStruct->sensorB;
  poly_packet_gett_field(newStruct->mPacket, PF_sensorName)->mData = (uint8_t*) &newStruct->sensorName;
  newStruct->mPacket->mBound = true;

  return newStruct;
}

blockreq_packet_t* new_blockreq()
{
  blockreq_packet_t* newStruct = (blockreq_packet_t*) malloc(sizeof(blockreq_packet_t));
  newStruct->mPacket = new_poly_packet(PP_blockReq);

  poly_packet_gett_field(newStruct->mPacket, PF_src)->mData = (uint8_t*) &newStruct->src;
  poly_packet_gett_field(newStruct->mPacket, PF_dst)->mData = (uint8_t*) &newStruct->dst;
  poly_packet_gett_field(newStruct->mPacket, PF_blockOffset)->mData = (uint8_t*) &newStruct->blockOffset;
  poly_packet_gett_field(newStruct->mPacket, PF_blockSize)->mData = (uint8_t*) &newStruct->blockSize;
  newStruct->mPacket->mBound = true;

  return newStruct;
}

blockresp_packet_t* new_blockresp()
{
  blockresp_packet_t* newStruct = (blockresp_packet_t*) malloc(sizeof(blockresp_packet_t));
  newStruct->mPacket = new_poly_packet(PP_blockResp);

  poly_packet_gett_field(newStruct->mPacket, PF_src)->mData = (uint8_t*) &newStruct->src;
  poly_packet_gett_field(newStruct->mPacket, PF_dst)->mData = (uint8_t*) &newStruct->dst;
  poly_packet_gett_field(newStruct->mPacket, PF_blockOffset)->mData = (uint8_t*) &newStruct->blockOffset;
  poly_packet_gett_field(newStruct->mPacket, PF_blockSize)->mData = (uint8_t*) &newStruct->blockSize;
  poly_packet_gett_field(newStruct->mPacket, PF_blockData)->mData = (uint8_t*) &newStruct->blockData;
  newStruct->mPacket->mBound = true;

  return newStruct;
}

