/**
  *@file SampleProtocol_proto.cpp
  *@brief generated protocol source code
  *@author make_protocol.py
  *@date 02/26/19
  */

/***********************************************************
        THIS FILE IS AUTOGENERATED. DO NOT MODIFY
***********************************************************/

#include "SampleProtocol_proto.h"

//Declare extern packet descriptors
poly_packet_desc_t* PP_SetData;
poly_packet_desc_t* PP_GetData;
poly_packet_desc_t* PP_RespData;
poly_packet_desc_t* PP_blockReq;
poly_packet_desc_t* PP_blockResp;


//Declare extern field descriptors
poly_field_desc_t* PF_src;
poly_field_desc_t* PF_dst;
poly_field_desc_t* PF_cmd;
poly_field_desc_t* PF_sensorA;
poly_field_desc_t* PF_sensorB;
poly_field_desc_t* PF_sensorName;
poly_field_desc_t* PF_blockOffset;
poly_field_desc_t* PF_blockSize;
poly_field_desc_t* PF_blockData;


void SampleProtocol_protocol_init()
{
  //Packet Descriptors
  PP_SetData = new_poly_packet_desc("SetData", 5 );
  PP_GetData = new_poly_packet_desc("GetData", 5 );
  PP_RespData = new_poly_packet_desc("RespData", 5 );
  PP_blockReq = new_poly_packet_desc("blockReq", 4 );
  PP_blockResp = new_poly_packet_desc("blockResp", 5 );


  //Field Descriptos
  PF_src = new_poly_field_desc("src", TYPE_UINT16 , 1 , FORMAT_HEX );
  PF_dst = new_poly_field_desc("dst", TYPE_UINT16 , 1 , FORMAT_HEX );
  PF_cmd = new_poly_field_desc("cmd", TYPE_UINT8 , 1 , FORMAT_HEX );
  PF_sensorA = new_poly_field_desc("sensorA", TYPE_INT16 , 1 , FORMAT_DEC );
  PF_sensorB = new_poly_field_desc("sensorB", TYPE_INT , 1 , FORMAT_DEC );
  PF_sensorName = new_poly_field_desc("sensorName", TYPE_STRING , 32 , FORMAT_ASCII );
  PF_blockOffset = new_poly_field_desc("blockOffset", TYPE_UINT32 , 1 , FORMAT_HEX );
  PF_blockSize = new_poly_field_desc("blockSize", TYPE_UINT32 , 1 , FORMAT_DEC );
  PF_blockData = new_poly_field_desc("blockData", TYPE_UINT8 , 64 , FORMAT_NONE );


  //Setting fields Descriptors for SetdataPacket
  poly_packet_desc_add_field(PP_SetData , PF_src , true );
  poly_packet_desc_add_field(PP_SetData , PF_dst , true );
  poly_packet_desc_add_field(PP_SetData , PF_sensorA , false );
  poly_packet_desc_add_field(PP_SetData , PF_sensorB , false );
  poly_packet_desc_add_field(PP_SetData , PF_sensorName , false );


  //Setting fields Descriptors for GetdataPacket
  poly_packet_desc_add_field(PP_GetData , PF_src , true );
  poly_packet_desc_add_field(PP_GetData , PF_dst , true );
  poly_packet_desc_add_field(PP_GetData , PF_sensorA , false );
  poly_packet_desc_add_field(PP_GetData , PF_sensorB , false );
  poly_packet_desc_add_field(PP_GetData , PF_sensorName , false );


  //Setting fields Descriptors for RespdataPacket
  poly_packet_desc_add_field(PP_RespData , PF_src , true );
  poly_packet_desc_add_field(PP_RespData , PF_dst , true );
  poly_packet_desc_add_field(PP_RespData , PF_sensorA , false );
  poly_packet_desc_add_field(PP_RespData , PF_sensorB , false );
  poly_packet_desc_add_field(PP_RespData , PF_sensorName , false );


  //Setting fields Descriptors for BlockreqPacket
  poly_packet_desc_add_field(PP_blockReq , PF_src , true );
  poly_packet_desc_add_field(PP_blockReq , PF_dst , true );
  poly_packet_desc_add_field(PP_blockReq , PF_blockOffset , true );
  poly_packet_desc_add_field(PP_blockReq , PF_blockSize , true );


  //Setting fields Descriptors for BlockrespPacket
  poly_packet_desc_add_field(PP_blockResp , PF_src , true );
  poly_packet_desc_add_field(PP_blockResp , PF_dst , true );
  poly_packet_desc_add_field(PP_blockResp , PF_blockOffset , true );
  poly_packet_desc_add_field(PP_blockResp , PF_blockSize , true );
  poly_packet_desc_add_field(PP_blockResp , PF_blockData , true );

}
/**********************************************************
              SetdataPacket                       
**********************************************************/


SetdataPacket::SetdataPacket(poly_packet_t* packet)
:PolyPacket(PP_SetData)
{  //Bind all fields
  getField(PF_src)->mData = (uint8_t*) &mSrc;
  getField(PF_dst)->mData = (uint8_t*) &mDst;
  getField(PF_sensorA)->mData = (uint8_t*) &mSensora;
  getField(PF_sensorB)->mData = (uint8_t*) &mSensorb;
  getField(PF_sensorName)->mData = (uint8_t*) &mSensorname;
  mPacket->mBound = true;
  copyFrom(packet);
}

void SetdataPacket::Src(uint16_t  val)
{
  hasField(PF_src,true);
  mSrc = val;
}

void SetdataPacket::Dst(uint16_t  val)
{
  hasField(PF_dst,true);
  mDst = val;
}

void SetdataPacket::Sensora(int16_t  val)
{
  hasField(PF_sensorA,true);
  mSensora = val;
}

void SetdataPacket::Sensorb(int  val)
{
  hasField(PF_sensorB,true);
  mSensorb = val;
}

void SetdataPacket::Sensorname(string  val)
{
  hasField(PF_sensorName,true);
  memcpy(mSensorname, val.c_str(), min((int)val.length() + 1,32));
}
/**********************************************************
              GetdataPacket                       
**********************************************************/


GetdataPacket::GetdataPacket(poly_packet_t* packet)
:PolyPacket(PP_GetData)
{  //Bind all fields
  getField(PF_src)->mData = (uint8_t*) &mSrc;
  getField(PF_dst)->mData = (uint8_t*) &mDst;
  getField(PF_sensorA)->mData = (uint8_t*) &mSensora;
  getField(PF_sensorB)->mData = (uint8_t*) &mSensorb;
  getField(PF_sensorName)->mData = (uint8_t*) &mSensorname;
  mPacket->mBound = true;
  copyFrom(packet);
}

void GetdataPacket::Src(uint16_t  val)
{
  hasField(PF_src,true);
  mSrc = val;
}

void GetdataPacket::Dst(uint16_t  val)
{
  hasField(PF_dst,true);
  mDst = val;
}

void GetdataPacket::Sensora(int16_t  val)
{
  hasField(PF_sensorA,true);
  mSensora = val;
}

void GetdataPacket::Sensorb(int  val)
{
  hasField(PF_sensorB,true);
  mSensorb = val;
}

void GetdataPacket::Sensorname(string  val)
{
  hasField(PF_sensorName,true);
  memcpy(mSensorname, val.c_str(), min((int)val.length() + 1,32));
}
/**********************************************************
              RespdataPacket                       
**********************************************************/


RespdataPacket::RespdataPacket(poly_packet_t* packet)
:PolyPacket(PP_RespData)
{  //Bind all fields
  getField(PF_src)->mData = (uint8_t*) &mSrc;
  getField(PF_dst)->mData = (uint8_t*) &mDst;
  getField(PF_sensorA)->mData = (uint8_t*) &mSensora;
  getField(PF_sensorB)->mData = (uint8_t*) &mSensorb;
  getField(PF_sensorName)->mData = (uint8_t*) &mSensorname;
  mPacket->mBound = true;
  copyFrom(packet);
}

void RespdataPacket::Src(uint16_t  val)
{
  hasField(PF_src,true);
  mSrc = val;
}

void RespdataPacket::Dst(uint16_t  val)
{
  hasField(PF_dst,true);
  mDst = val;
}

void RespdataPacket::Sensora(int16_t  val)
{
  hasField(PF_sensorA,true);
  mSensora = val;
}

void RespdataPacket::Sensorb(int  val)
{
  hasField(PF_sensorB,true);
  mSensorb = val;
}

void RespdataPacket::Sensorname(string  val)
{
  hasField(PF_sensorName,true);
  memcpy(mSensorname, val.c_str(), min((int)val.length() + 1,32));
}
/**********************************************************
              BlockreqPacket                       
**********************************************************/


BlockreqPacket::BlockreqPacket(poly_packet_t* packet)
:PolyPacket(PP_blockReq)
{  //Bind all fields
  getField(PF_src)->mData = (uint8_t*) &mSrc;
  getField(PF_dst)->mData = (uint8_t*) &mDst;
  getField(PF_blockOffset)->mData = (uint8_t*) &mBlockoffset;
  getField(PF_blockSize)->mData = (uint8_t*) &mBlocksize;
  mPacket->mBound = true;
  copyFrom(packet);
}

void BlockreqPacket::Src(uint16_t  val)
{
  hasField(PF_src,true);
  mSrc = val;
}

void BlockreqPacket::Dst(uint16_t  val)
{
  hasField(PF_dst,true);
  mDst = val;
}

void BlockreqPacket::Blockoffset(uint32_t  val)
{
  hasField(PF_blockOffset,true);
  mBlockoffset = val;
}

void BlockreqPacket::Blocksize(uint32_t  val)
{
  hasField(PF_blockSize,true);
  mBlocksize = val;
}

/**********************************************************
              BlockrespPacket                       
**********************************************************/


BlockrespPacket::BlockrespPacket(poly_packet_t* packet)
:PolyPacket(PP_blockResp)
{  //Bind all fields
  getField(PF_src)->mData = (uint8_t*) &mSrc;
  getField(PF_dst)->mData = (uint8_t*) &mDst;
  getField(PF_blockOffset)->mData = (uint8_t*) &mBlockoffset;
  getField(PF_blockSize)->mData = (uint8_t*) &mBlocksize;
  getField(PF_blockData)->mData = (uint8_t*) &mBlockdata;
  mPacket->mBound = true;
  copyFrom(packet);
}

void BlockrespPacket::Src(uint16_t  val)
{
  hasField(PF_src,true);
  mSrc = val;
}

void BlockrespPacket::Dst(uint16_t  val)
{
  hasField(PF_dst,true);
  mDst = val;
}

void BlockrespPacket::Blockoffset(uint32_t  val)
{
  hasField(PF_blockOffset,true);
  mBlockoffset = val;
}

void BlockrespPacket::Blocksize(uint32_t  val)
{
  hasField(PF_blockSize,true);
  mBlocksize = val;
}

void BlockrespPacket::Blockdata(uint8_t*  val)
{
  hasField(PF_blockData,true);
  memcpy(mBlockdata, val, 64 * sizeof(uint8_t));
}
