/**
  *@file SampleProtocol.h
  *@brief generated protocol source code
  *@author make_protocol.py
  *@date 03/18/19
  */

/***********************************************************
        THIS FILE IS AUTOGENERATED. DO NOT MODIFY
***********************************************************/
#include "Utilities/PolyPacket/poly_service.h"


typedef enum{
  SP_CMD_TEST,
  SP_CMD_SEND,
  SP_CMD_STOP,
  SP_CMD_MAX_LIMIT
} sp_cmd_e;



//Declare extern packet descriptors
extern poly_packet_desc_t* SP_ACK_PACKET;
extern poly_packet_desc_t* SP_SETDATA_PACKET;
extern poly_packet_desc_t* SP_GETDATA_PACKET;
extern poly_packet_desc_t* SP_RESPDATA_PACKET;
extern poly_packet_desc_t* SP_BLOCKREQ_PACKET;
extern poly_packet_desc_t* SP_BLOCKRESP_PACKET;


//Declare extern field descriptors
extern poly_field_desc_t* SP_SRC_FIELD;
extern poly_field_desc_t* SP_DST_FIELD;
extern poly_field_desc_t* SP_CMD_FIELD;
extern poly_field_desc_t* SP_SENSORA_FIELD;
extern poly_field_desc_t* SP_SENSORB_FIELD;
extern poly_field_desc_t* SP_SENSORNAME_FIELD;
extern poly_field_desc_t* SP_BLOCKOFFSET_FIELD;
extern poly_field_desc_t* SP_BLOCKSIZE_FIELD;
extern poly_field_desc_t* SP_BLOCKDATA_FIELD;

/*@brief The main type dealt with by the user
 *@note just wraps a poly_packet to prevent mixing them when multiple protocol are in use
 */
typedef struct{
  poly_packet_t mPacket;    //internal packet structure
}sp_packet_t;


/*******************************************************************************
  Service Functions
*******************************************************************************/
/**
*@brief initializes protocol service
*@param ifaces number of interfaces to use
*/
void sp_service_init(int interfaceCount);

/**
  *@brief processes data in buffers
  */
void sp_service_process();

/**
  *@brief sends packet over given interface
  *@param metaPacket packet to be sent
  *@param iface index of interface to send on
  */
void sp_service_register_tx( int iface, poly_tx_callback txCallBack);

/**
  *@brief 'Feeds' bytes to service at given interface for processing
  *@param iface index of interface to send on
  *@param data data to be processed
  *@param number of bytes
  */
void sp_service_feed(int iface, uint8_t* data, int len);

/**
  *@brief sends packet over given interface
  *@param metaPacket packet to be sent
  *@param iface index of interface to send on
  */
HandlerStatus_e sp_send( int iface, sp_packet_t* metaPacket);

/**
  *@brief enables/disables the auto acknowledgement function of the service
  *@param enable true enable auto acks, false disables them
  */
void sp_auto_ack(bool enable);


/*******************************************************************************
  Meta-Packet Functions
*******************************************************************************/

/**
  *@brief creates a new sp_packet_t object OWNER IS RESPONSIBLE FOR DESTROYING
  *@param desc ptr to packet descriptor to model packet from
  *@return ptr to new {proto.prefix}_packet_t
  */
sp_packet_t* new_sp_packet(poly_packet_desc_t* desc);


/**
  *@brief recrusively destroys sp_packet_t and its contents
  *@param metaPacket metapacket to destroy
  */
void sp_destroy(sp_packet_t* metaPacket);

/**
  *@brief converts packet to json
  *@param packet ptr to packet to convert
  *@param buf buffer to store string
  *@return length of string
  */
#define sp_print_json(packet,buf) poly_packet_print_json(&packet->mPacket, buf, false)

/**
  *@brief parses packet from a buffer of data
  *@param packet ptr to packet to be built
  *@param buf buffer to parse
  *@return status of parse attempt
  */
#define sp_parse(packet,buf,len) poly_packet_parse_buffer(&packet->mPacket, buf, len)


/**
  *@brief packs packet into a byte array
  *@param packet ptr to packet to be packed
  *@param buf buffer to store data
  *@return length of packed data
  */
#define sp_pack(packet, buf) poly_packet_pack(&packet->mPacket, buf)


/*******************************************************************************
  Meta-Packet setters
*******************************************************************************/
void sp_setSrc(sp_packet_t* packet, uint16_t val);
void sp_setDst(sp_packet_t* packet, uint16_t val);
void sp_setCmd(sp_packet_t* packet, uint8_t val);
void sp_setSensora(sp_packet_t* packet, int16_t val);
void sp_setSensorb(sp_packet_t* packet, int val);
void sp_setSensorname(sp_packet_t* packet, const char* val);
void sp_setBlockoffset(sp_packet_t* packet, uint32_t val);
void sp_setBlocksize(sp_packet_t* packet, uint32_t val);
void sp_setBlockdata(sp_packet_t* packet, const uint8_t* val);

/*******************************************************************************
  Meta-Packet getters
*******************************************************************************/
uint16_t sp_getSrc(sp_packet_t* packet);
uint16_t sp_getDst(sp_packet_t* packet);
uint8_t sp_getCmd(sp_packet_t* packet);
int16_t sp_getSensora(sp_packet_t* packet);
int sp_getSensorb(sp_packet_t* packet);
char* sp_getSensorname(sp_packet_t* packet);
uint32_t sp_getBlockoffset(sp_packet_t* packet);
uint32_t sp_getBlocksize(sp_packet_t* packet);
uint8_t* sp_getBlockdata(sp_packet_t* packet);

/*******************************************************************************
  Packet Handlers
*******************************************************************************/
/*@brief Handler for ack packets */
HandlerStatus_e sp_ack_handler(sp_packet_t* ack);

/*@brief Handler for SetData packets */
HandlerStatus_e sp_setdata_handler(sp_packet_t* SetData, sp_packet_t* RespData);

/*@brief Handler for GetData packets */
HandlerStatus_e sp_getdata_handler(sp_packet_t* GetData, sp_packet_t* RespData);

/*@brief Handler for RespData packets */
HandlerStatus_e sp_respdata_handler(sp_packet_t* RespData);

/*@brief Handler for blockReq packets */
HandlerStatus_e sp_blockreq_handler(sp_packet_t* blockReq, sp_packet_t* blockResp);

/*@brief Handler for blockResp packets */
HandlerStatus_e sp_blockresp_handler(sp_packet_t* blockResp);

/*@brief Catch-All Handler for unhandled packets */
HandlerStatus_e sp_default_handler(sp_packet_t * packet);