/**
  *@file app_minimal.cpp
  *@brief generated protocol source code
  *@author make_protocol.py
  *@date 03/24/19
  */

/***********************************************************
        THIS FILE IS AUTOGENERATED. DO NOT MODIFY
***********************************************************/

#include "app_minimal.h"

static uint8_t iface0_rx_buf[512];

static inline HandlerStatus_e iface0_write(uint8_t* data, int len)
{
  /* Place code for writing bytes on interface 0 here */
  //TODO write to interface (i.e. uart,spi, etc)

  return PACKET_SENT;
}


static inline void iface0_read()
{
  int len;
  /* Place code for reading bytes from interface 0 here */
  //TODO read bytes from interface to iface0_rx_buf

  pp_service_feed(0,iface0_rx_buf, len);
}

/*******************************************************************************
  App Init
*******************************************************************************/

void app_minimal_init()
{
  /* initialize peripheral for iface_0 */
  //TODO initialize peripheral for iface_0

  //initialize service
  pp_service_init(1);

  pp_service_register_tx(0, iface0_write);

}

/*******************************************************************************
  App Process
*******************************************************************************/

void app_minimal_process()
{
  /* read in new data from iface 0*/
  iface0_read();

  /* process the actual service */
  pp_service_process();

}


/*******************************************************************************
  Packet handlers
*******************************************************************************/
/**
  *@brief Handler for receiving AmbientData packets
  *@param AmbientData incoming AmbientData packet
  *@return handling status
  */
HandlerStatus_e pp_AmbientData_handler(pp_packet_t* pp_AmbientData)
{
  /*  Get Required Fields in packet */
  int ambient = pp_getAmbient(pp_AmbientData);


  return PACKET_HANDLED;
}

/**
  *@brief Handler for receiving RequestAmbient packets
  *@param RequestAmbient incoming RequestAmbient packet
  *@param AmbientData AmbientData packet to respond with
  *@return handling status
  */
HandlerStatus_e pp_RequestAmbient_handler(pp_packet_t* pp_RequestAmbient, pp_packet_t* pp_AmbientData)
{
  /*  Get Required Fields in packet */
  /*    Set required Fields in response  */
  //pp_setAmbient(pp_AmbientData, value );                   //Set ambient value


  return PACKET_HANDLED;
}


/**
  *@brief catch-all handler for any packet not handled by its default handler
  *@param metaPacket ptr to pp_packet_t containing packet
  *@return handling status
  */
HandlerStatus_e pp_default_handler( pp_packet_t * pp_packet)
{


  return PACKET_HANDLED;
}