/**
  *@file SampleService.c
  *@brief generated code for Sample packet service
  *@author make_protocol.py
  *@date 04/01/19
  */

/***********************************************************
        THIS FILE IS AUTOGENERATED. DO NOT MODIFY
***********************************************************/

#include "SampleService.h"
#include <assert.h>

//Define packet IDs
#define SP_PACKET_PING_ID 0
#define SP_PACKET_ACK_ID 1
#define SP_PACKET_SENDCMD_ID 2
#define SP_PACKET_GETDATA_ID 3
#define SP_PACKET_DATA_ID 4


//Global descriptors
poly_packet_desc_t* SP_PACKET_PING;
poly_packet_desc_t* SP_PACKET_ACK;
poly_packet_desc_t* SP_PACKET_SENDCMD;
poly_packet_desc_t* SP_PACKET_GETDATA;
poly_packet_desc_t* SP_PACKET_DATA;

poly_field_desc_t* SP_FIELD_CMD;
poly_field_desc_t* SP_FIELD_SENSORA;
poly_field_desc_t* SP_FIELD_SENSORB;
poly_field_desc_t* SP_FIELD_SENSORNAME;

//Global descriptors
poly_packet_desc_t _SP_PACKET_PING;
poly_packet_desc_t _SP_PACKET_ACK;
poly_packet_desc_t _SP_PACKET_SENDCMD;
poly_packet_desc_t _SP_PACKET_GETDATA;
poly_packet_desc_t _SP_PACKET_DATA;

poly_field_desc_t _SP_FIELD_CMD;
poly_field_desc_t _SP_FIELD_SENSORA;
poly_field_desc_t _SP_FIELD_SENSORB;
poly_field_desc_t _SP_FIELD_SENSORNAME;

static poly_service_t SP_SERVICE;

/*******************************************************************************
  Service Functions
*******************************************************************************/

/**
  *@brief initializes sp_protocol
  *@param interfaceCount number of interfaces to create
  */
void sp_service_init(int interfaceCount)
{
  //initialize core service
  poly_service_init(&SP_SERVICE,5, interfaceCount);

  //Build Packet Descriptors
  SP_PACKET_PING = poly_packet_desc_init(&_SP_PACKET_PING ,SP_PACKET_PING_ID,"Ping", 0);
  SP_PACKET_ACK = poly_packet_desc_init(&_SP_PACKET_ACK ,SP_PACKET_ACK_ID,"Ack", 0);
  SP_PACKET_SENDCMD = poly_packet_desc_init(&_SP_PACKET_SENDCMD ,SP_PACKET_SENDCMD_ID,"SendCmd", 1);
  SP_PACKET_GETDATA = poly_packet_desc_init(&_SP_PACKET_GETDATA ,SP_PACKET_GETDATA_ID,"GetData", 0);
  SP_PACKET_DATA = poly_packet_desc_init(&_SP_PACKET_DATA ,SP_PACKET_DATA_ID,"Data", 3);

  //Build Field Descriptors
  SP_FIELD_CMD = poly_field_desc_init( &_SP_FIELD_CMD ,"cmd", TYPE_UINT8, 1, FORMAT_HEX);
  SP_FIELD_SENSORA = poly_field_desc_init( &_SP_FIELD_SENSORA ,"sensorA", TYPE_INT16, 1, FORMAT_DEC);
  SP_FIELD_SENSORB = poly_field_desc_init( &_SP_FIELD_SENSORB ,"sensorB", TYPE_INT, 1, FORMAT_DEC);
  SP_FIELD_SENSORNAME = poly_field_desc_init( &_SP_FIELD_SENSORNAME ,"sensorName", TYPE_STRING, 32, FORMAT_ASCII);



  //Setting Field Descriptors for SendCmd
  poly_packet_desc_add_field(SP_PACKET_SENDCMD , SP_FIELD_CMD , true );


  //Setting Field Descriptors for Data
  poly_packet_desc_add_field(SP_PACKET_DATA , SP_FIELD_SENSORA , false );
  poly_packet_desc_add_field(SP_PACKET_DATA , SP_FIELD_SENSORB , false );
  poly_packet_desc_add_field(SP_PACKET_DATA , SP_FIELD_SENSORNAME , false );


  //Register packet descriptors with the service
  poly_service_register_desc(&SP_SERVICE, SP_PACKET_PING);
  poly_service_register_desc(&SP_SERVICE, SP_PACKET_ACK);
  poly_service_register_desc(&SP_SERVICE, SP_PACKET_SENDCMD);
  poly_service_register_desc(&SP_SERVICE, SP_PACKET_GETDATA);
  poly_service_register_desc(&SP_SERVICE, SP_PACKET_DATA);

  poly_service_start(&SP_SERVICE, 16);

}


void sp_service_teardown()
{
  //deinit Packet Descriptors
  SP_PACKET_PING = poly_packet_desc_deinit(&_SP_PACKET_PING);
  SP_PACKET_ACK = poly_packet_desc_deinit(&_SP_PACKET_ACK);
  SP_PACKET_SENDCMD = poly_packet_desc_deinit(&_SP_PACKET_SENDCMD);
  SP_PACKET_GETDATA = poly_packet_desc_deinit(&_SP_PACKET_GETDATA);
  SP_PACKET_DATA = poly_packet_desc_deinit(&_SP_PACKET_DATA);

  //deinitialize core service
  poly_service_deinit(&SP_SERVICE);

}

/**
  *@brief attempts to process data in buffers and parse out packets
  */
void sp_service_process()
{
  static sp_packet_t packet;
  static sp_packet_t response;

  HandlerStatus_e status = PACKET_NOT_HANDLED;

  //reset states of static packets
  packet.mBuilt = false;
  packet.mSpooled = false;
  response.mSpooled = false;
  response.mBuilt = false;

  if(poly_service_try_parse(&SP_SERVICE, &packet.mPacket) == PACKET_VALID)
  {
    //if we get here, then the inner packet was built by the parser
    packet.mBuilt = true;

    //Dispatch packet
    switch(packet.mPacket.mDesc->mTypeId)
    {
      case SP_PACKET_PING_ID:
        sp_packet_build(&response, SP_PACKET_ACK);
        status = sp_Ping_handler(&packet, &response);
        break;
      case SP_PACKET_ACK_ID:
        status = sp_Ack_handler(&packet);
        break;
      case SP_PACKET_SENDCMD_ID:
        status = sp_SendCmd_handler(&packet);
        break;
      case SP_PACKET_GETDATA_ID:
       sp_packet_build(&response, SP_PACKET_DATA);
       status = sp_GetData_handler(&packet , &response );
        break;
      case SP_PACKET_DATA_ID:
        status = sp_Data_handler(&packet);
        break;
      default:
        //we should never get here
        assert(false);
        break;
    }

    //If this packet doe not have an explicit response and AutoAck is enabled, create an ack packet
    if(( SP_SERVICE.mAutoAck ) && (!response.mBuilt) && (!(packet.mPacket.mHeader.mToken & POLY_ACK_FLAG)))
    {
      sp_packet_build(&response, SP_PACKET_ACK);
    }

    //If the packet was not handled, throw it to the default handler
    if(status == PACKET_NOT_HANDLED)
    {
      status = sp_default_handler(&packet);
    }


    //If a response has been build and the status was not set to ignore, we send a response on the intrface it came from
    if(( status == PACKET_HANDLED) && (response.mBuilt) )
    {
      //set response token with ack flag
			response.mPacket.mHeader.mToken = packet.mPacket.mHeader.mToken | POLY_ACK_FLAG;

      sp_send(packet.mPacket.mInterface , &response);
    }

    //Clean the packets
    sp_clean(&packet);
    sp_clean(&response);
  }

  //despool any packets ready to go out
  poly_service_despool(&SP_SERVICE);

}


void sp_service_register_tx( int iface, poly_tx_callback txCallBack)
{
  poly_service_register_tx_callback(&SP_SERVICE, iface,txCallBack);
}

void sp_service_feed(int iface, uint8_t* data, int len)
{
  poly_service_feed(&SP_SERVICE,iface,data,len);
}

HandlerStatus_e sp_send(int iface, sp_packet_t* packet)
{
  HandlerStatus_e status;

  status = poly_service_spool(&SP_SERVICE, iface, &packet->mPacket);

  if(status == PACKET_SPOOLED)
  {
    packet->mSpooled = true;
  }

  return status;
}

void sp_auto_ack(bool enable)
{
  SP_SERVICE.mAutoAck = enable;
}


/*******************************************************************************
  Meta packet
*******************************************************************************/

/**
  *@brief initializes a new {proto.prefix}_packet_t
  *@param desc ptr to packet descriptor to model packet from
  */
void sp_packet_build(sp_packet_t* packet, poly_packet_desc_t* desc)
{
  //create new allocated packet
  poly_packet_build(&packet->mPacket, desc, true);
  packet->mBuilt = true;
  packet->mSpooled = false;
}


/**
  *@brief frees memory allocated for metapacket
  *@param packet ptr to metaPacket
  *
  */
void sp_clean(sp_packet_t* packet)
{
  //If the packet has been spooled, the spool is responsible for it now
  if(packet->mBuilt && (!packet->mSpooled))
  {
    poly_packet_clean(&packet->mPacket);
  }

}

int sp_fieldLen(sp_packet_t* packet, poly_field_desc_t* fieldDesc )
{
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, SP_FIELD_SENSORNAME);
  return (int)field->mSize;
}

/*******************************************************************************

  Meta-Packet setters

*******************************************************************************/

/**
  *@brief Sets value of cmd field
  *@param packet ptr to sp_packet
  *@param val uint8_t to set field to
  */
void sp_setCmd(sp_packet_t* packet, uint8_t val)
{
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, SP_FIELD_CMD);
  poly_field_set(field,( const uint8_t*) &val);
}

/**
  *@brief Sets value of sensorA field
  *@param packet ptr to sp_packet
  *@param val int16_t to set field to
  */
void sp_setSensorA(sp_packet_t* packet, int16_t val)
{
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, SP_FIELD_SENSORA);
  poly_field_set(field,( const uint8_t*) &val);
}

/**
  *@brief Sets value of sensorB field
  *@param packet ptr to sp_packet
  *@param val int to set field to
  */
void sp_setSensorB(sp_packet_t* packet, int val)
{
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, SP_FIELD_SENSORB);
  poly_field_set(field,( const uint8_t*) &val);
}

/**
  *@brief Sets value(s) in sensorName field
  *@param packet ptr to sp_packet
  *@param val char* to copy data from
  */
void sp_setSensorName(sp_packet_t* packet, const char* val)
{
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, SP_FIELD_SENSORNAME);
  poly_field_set(field,( const uint8_t*) val);
}


/*******************************************************************************
  Meta-Packet getters
*******************************************************************************/

/**
  *@brief Gets value of cmd field
  *@param packet ptr to sp_packet
  *@return uint8_t data from field
  */
uint8_t sp_getCmd(sp_packet_t* packet)
{
  uint8_t val;
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, SP_FIELD_CMD);
  poly_field_get(field,(uint8_t*) &val);
  return val;
}

/**
  *@brief Gets value of sensorA field
  *@param packet ptr to sp_packet
  *@return int16_t data from field
  */
int16_t sp_getSensorA(sp_packet_t* packet)
{
  int16_t val;
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, SP_FIELD_SENSORA);
  poly_field_get(field,(uint8_t*) &val);
  return val;
}

/**
  *@brief Gets value of sensorB field
  *@param packet ptr to sp_packet
  *@return int data from field
  */
int sp_getSensorB(sp_packet_t* packet)
{
  int val;
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, SP_FIELD_SENSORB);
  poly_field_get(field,(uint8_t*) &val);
  return val;
}

/**
  *@brief Gets value of sensorName field
  *@param packet ptr to sp_packet
  *@return char* of data in field
  */
char* sp_getSensorName(sp_packet_t* packet)
{
  char* val;
  poly_field_t* field = poly_packet_get_field(&packet->mPacket, SP_FIELD_SENSORNAME);
  val = (char*)poly_field_get(field, NULL);
  return val;
}


/*******************************************************************************
  Quick send functions
*******************************************************************************/

HandlerStatus_e sp_sendPing(int iface)
{
  HandlerStatus_e status;
  //create packet
  sp_packet_t packet;
  sp_packet_build(&packet, SP_PACKET_PING);

  status = sp_send(iface,&packet); //send packet
  sp_clean(&packet); //This will only free the underlying packet if the spooling was unsuccessful
  return status;
}

/**
  *@brief sends SendCmd packet
  *@param iface indec of interface to send packet to
  *@param cmd value to set cmd field to
  *@return status send attempt
  */
HandlerStatus_e sp_sendSendCmd(int iface, uint8_t cmd)
{
  HandlerStatus_e status;
  //create packet
  sp_packet_t packet;
  sp_packet_build(&packet,SP_PACKET_SENDCMD);

  //set fields
  sp_setCmd(&packet, cmd);

  status = sp_send(iface,&packet); //send packet
  sp_clean(&packet); //This will only free the underlying packet if the spooling was unsuccessful
  return status;
}
/**
  *@brief sends GetData packet
  *@param iface indec of interface to send packet to
  *@return status send attempt
  */
HandlerStatus_e sp_sendGetData(int iface)
{
  HandlerStatus_e status;
  //create packet
  sp_packet_t packet;
  sp_packet_build(&packet,SP_PACKET_GETDATA);

  //set fields

  status = sp_send(iface,&packet); //send packet
  sp_clean(&packet); //This will only free the underlying packet if the spooling was unsuccessful
  return status;
}
/**
  *@brief sends Data packet
  *@param iface indec of interface to send packet to
  *@param sensorA value to set sensorA field to
  *@param sensorB value to set sensorB field to
  *@param sensorName char* to sensorName field from
  *@return status send attempt
  */
HandlerStatus_e sp_sendData(int iface, int16_t sensorA, int sensorB, const char* sensorName)
{
  HandlerStatus_e status;
  //create packet
  sp_packet_t packet;
  sp_packet_build(&packet,SP_PACKET_DATA);

  //set fields
  sp_setSensorA(&packet, sensorA);
  sp_setSensorB(&packet, sensorB);
  sp_setSensorName(&packet, sensorName);

  status = sp_send(iface,&packet); //send packet
  sp_clean(&packet); //This will only free the underlying packet if the spooling was unsuccessful
  return status;
}


/*******************************************************************************
  Weak packet handlers

  Do not modify these, just create your own without the '__weak' attribute
*******************************************************************************/
/**
  *@brief Handler for receiving ping packets
  *@param sp_ping ptr to incoming ping packet
  *@param sp_ack ptr to repsonding ack
  *@return PACKET_HANDLED
  */
__attribute__((weak)) HandlerStatus_e sp_Ping_handler(sp_packet_t* sp_ping, sp_packet_t* sp_ack)
{
  /* Ack token has already been set as ping token with POLY_ACK_FLAG*/
  return PACKET_HANDLED;
}

/**
  *@brief Handler for receiving ack packets
  *@param sp_ack ptr to ack
  *@return PACKET_HANDLED
  */
__attribute__((weak)) HandlerStatus_e sp_Ack_handler(sp_packet_t* sp_ack)
{
  return PACKET_HANDLED;
}

/**
  *@brief Handler for receiving SendCmd packets
  *@param SendCmd incoming SendCmd packet
  *@return handling status
  */
__attribute__((weak)) HandlerStatus_e sp_SendCmd_handler(sp_packet_t* sp_SendCmd)
{
  /*  Get Required Fields in packet */
  //uint8_t cmd = sp_getCmd(sp_SendCmd); //command byte for controlling node


  /* NOTE : This function should not be modified! If needed,  It should be overridden in the application code */

  return PACKET_NOT_HANDLED;
}

/**
  *@brief Handler for receiving GetData packets
  *@param GetData incoming GetData packet
  *@param Data Data packet to respond with
  *@return handling status
  */
__attribute__((weak)) HandlerStatus_e sp_GetData_handler(sp_packet_t* sp_GetData, sp_packet_t* sp_Data)
{
  /*  Get Required Fields in packet */
  /*    Set required Fields in response  */


  /* NOTE : This function should not be modified! If needed,  It should be overridden in the application code */

  return PACKET_NOT_HANDLED;
}

/**
  *@brief Handler for receiving Data packets
  *@param Data incoming Data packet
  *@return handling status
  */
__attribute__((weak)) HandlerStatus_e sp_Data_handler(sp_packet_t* sp_Data)
{
  /*  Get Required Fields in packet */


  /* NOTE : This function should not be modified! If needed,  It should be overridden in the application code */

  return PACKET_NOT_HANDLED;
}


/**
  *@brief catch-all handler for any packet not handled by its default handler
  *@param metaPacket ptr to sp_packet_t containing packet
  *@return handling status
  */
__attribute__((weak)) HandlerStatus_e sp_default_handler( sp_packet_t * sp_packet)
{

  /* NOTE : This function should not be modified, when the callback is needed,
          sp_default_handler  should be implemented in the user file
  */

  return PACKET_NOT_HANDLED;
}