/**
  *@file SampleService.h
  *@brief generated code for Sample packet service
  *@author make_protocol.py
  *@date 04/01/19
  *@hash 67837EF9
  */

/***********************************************************
        THIS FILE IS AUTOGENERATED. DO NOT MODIFY
***********************************************************/
#include "Utilities/PolyPacket/poly_service.h"

#define SP_SERVICE_HASH 0x67837EF9

/*******************************************************************************
  Enums
*******************************************************************************/
/* Enums for cmd field */
typedef enum{
  SP_CMD_LED_ON,              /* turns on led */
  SP_CMD_LED_OFF,              /* turns off led */
  SP_CMD_RESET,              /* resets the device */
  SP_CMD_MAX_LIMIT
} sp_cmd_e;


/*******************************************************************************
  Bits/Flags
*******************************************************************************/

/*******************************************************************************
  Global Descriptors
*******************************************************************************/
//Declare extern packet descriptors
extern poly_packet_desc_t* SP_PACKET_PING;
extern poly_packet_desc_t* SP_PACKET_ACK;
extern poly_packet_desc_t* SP_PACKET_SENDCMD;
extern poly_packet_desc_t* SP_PACKET_GETDATA;
extern poly_packet_desc_t* SP_PACKET_DATA;


//Declare extern field descriptors
extern poly_field_desc_t* SP_FIELD_CMD;
extern poly_field_desc_t* SP_FIELD_SENSORA;
extern poly_field_desc_t* SP_FIELD_SENSORB;
extern poly_field_desc_t* SP_FIELD_SENSORNAME;

/*@brief The main type dealt with by the user
 *@note just wraps a poly_packet to prevent mixing them when multiple protocol are in use
 */
typedef struct{
  poly_packet_t mPacket;    //internal packet structure
  bool mSpooled;            //spooled data doesnt get cleaned, the spool owns it now
  bool mBuilt;
}sp_packet_t;


/*******************************************************************************
  Service Functions
*******************************************************************************/
/**
  *@brief initializes protocol service
  *@param ifaces number of interfaces to use
  */
void sp_service_init(int interfaceCount);

/**
  *@brief tears down service
  *@note probably not needed based on lifecycle of service
  *@ but useful for detecting memory leaks
  */
void sp_service_teardown();

/**
  *@brief processes data in buffers
  */
void sp_service_process();

/**
  *@brief registers a callback to let the service know how to send bytes for a given interface
  *@param iface index of interface to register with
  *@param txCallBack a function pointer for the callback
  */
void sp_service_register_tx( int iface, poly_tx_callback txCallBack);

/**
  *@brief 'Feeds' bytes to service at given interface for processing
  *@param iface index of interface to send on
  *@param data data to be processed
  *@param number of bytes
  */
void sp_service_feed(int iface, uint8_t* data, int len);

/**
  *@brief sends packet over given interface
  *@param packet packet to be sent
  *@param iface index of interface to send on
  */
HandlerStatus_e sp_send( int iface, sp_packet_t* packet);

/**
  *@brief enables/disables the auto acknowledgement function of the service
  *@param enable true enable auto acks, false disables them
  */
void sp_auto_ack(bool enable);


/*******************************************************************************
  Meta-Packet Functions
*******************************************************************************/

/**
  *@brief initializes a new {proto.prefix}_packet_t
  *@param desc ptr to packet descriptor to model packet from
  */
void sp_packet_build(sp_packet_t* packet, poly_packet_desc_t* desc);


/**
  *@brief recrusively cleans packet and its contents if it still has ownership
  *@param packet packet to clean
  */
void sp_clean(sp_packet_t* packet);

/**
  *@brief converts packet to json
  *@param packet ptr to packet to convert
  *@param buf buffer to store string
  *@return length of string
  */
#define sp_print_json(packet,buf) poly_packet_print_json(&(packet)->mPacket, buf, false)

/**
  *@brief parses packet from a buffer of data
  *@param packet ptr to packet to be built
  *@param buf buffer to parse
  *@return status of parse attempt
  */
#define sp_parse(packet,buf,len) poly_packet_parse_buffer(&(packet)->mPacket, buf, len)


/**
  *@brief packs packet into a byte array
  *@param packet ptr to packet to be packed
  *@param buf buffer to store data
  *@return length of packed data
  */
#define sp_pack(packet, buf) poly_packet_pack(&(packet)->mPacket, buf)

/**
  *@brief gets the length of a give field in a packet
  *@param packet ptr to sp_packet_t
  *@param field ptr to field descriptor
  *@return size of field
  */
int sp_fieldLen(sp_packet_t* packet, poly_field_desc_t* fieldDesc );

/*******************************************************************************
  Meta-Packet setters
*******************************************************************************/
void sp_setCmd(sp_packet_t* packet, uint8_t val);
void sp_setSensorA(sp_packet_t* packet, int16_t val);
void sp_setSensorB(sp_packet_t* packet, int val);
void sp_setSensorName(sp_packet_t* packet, const char* val);

/*******************************************************************************
  Meta-Packet getters
*******************************************************************************/
uint8_t sp_getCmd(sp_packet_t* packet);
int16_t sp_getSensorA(sp_packet_t* packet);
int sp_getSensorB(sp_packet_t* packet);
char* sp_getSensorName(sp_packet_t* packet);

/*******************************************************************************
  Quick send functions

  These are convenience one-liner functions for sending messages.
  They also handle their own clean up and are less bug prone than building your own packets
*******************************************************************************/

/**
  *@brief Sends a ping
  *@param iface interface to ping
  *@note a ping is just an ACK without the ack flag set in the token
  */
HandlerStatus_e sp_sendPing(int iface);

HandlerStatus_e sp_sendSendCmd(int iface, uint8_t cmd);
HandlerStatus_e sp_sendGetData(int iface);
HandlerStatus_e sp_sendData(int iface, int16_t sensorA, int sensorB, const char* sensorName);

/*******************************************************************************
  Packet Handlers
*******************************************************************************/
/*@brief Handler for Ping packets */
HandlerStatus_e sp_Ping_handler(sp_packet_t* sp_Ping, sp_packet_t* sp_Ack);

/*@brief Handler for Ack packets */
HandlerStatus_e sp_Ack_handler(sp_packet_t* sp_Ack);

/*@brief Handler for SendCmd packets */
HandlerStatus_e sp_SendCmd_handler(sp_packet_t* sp_SendCmd);

/*@brief Handler for GetData packets */
HandlerStatus_e sp_GetData_handler(sp_packet_t* sp_GetData, sp_packet_t* sp_Data);

/*@brief Handler for Data packets */
HandlerStatus_e sp_Data_handler(sp_packet_t* sp_Data);

/*@brief Catch-All Handler for unhandled packets */
HandlerStatus_e sp_default_handler(sp_packet_t * sp_packet);