/**
  *@file SampleProtocol.cpp
  *@brief generated protocol source code
  *@author make_protocol.py
  *@date 03/18/19
  */

/***********************************************************
        THIS FILE IS AUTOGENERATED. DO NOT MODIFY
***********************************************************/

#include "SampleProtocol.h"
#include "Utilities/PolyPacket/poly_parser.h"

//Global descriptors
  poly_packet_desc_t* PP_ack
  poly_packet_desc_t* PP_SetData
  poly_packet_desc_t* PP_GetData
  poly_packet_desc_t* PP_RespData
  poly_packet_desc_t* PP_blockReq
  poly_packet_desc_t* PP_blockResp

  poly_field_desc_t* PF_src
  poly_field_desc_t* PF_dst
  poly_field_desc_t* PF_cmd
  poly_field_desc_t* PF_sensorA
  poly_field_desc_t* PF_sensorB
  poly_field_desc_t* PF_sensorName
  poly_field_desc_t* PF_blockOffset
  poly_field_desc_t* PF_blockSize
  poly_field_desc_t* PF_blockData

poly_parser_t* sp_PARSER;

void sp_protocol_init(int ifaces)
{

  sp_PARSER = new_poly_parser(6, ifaces);

  //Build Packet Descriptors
  PP_ack = new_poly_packet_desc("ack", 0);
  PP_SetData = new_poly_packet_desc("SetData", 5);
  PP_GetData = new_poly_packet_desc("GetData", 5);
  PP_RespData = new_poly_packet_desc("RespData", 5);
  PP_blockReq = new_poly_packet_desc("blockReq", 4);
  PP_blockResp = new_poly_packet_desc("blockResp", 5);

  //Build Field Descriptors
  PF_src = new_poly_field_desc("blockResp", TYPE_UINT16, 1, FORMAT_HEX);
  PF_dst = new_poly_field_desc("blockResp", TYPE_UINT16, 1, FORMAT_HEX);
  PF_cmd = new_poly_field_desc("blockResp", TYPE_UINT8, 1, FORMAT_HEX);
  PF_sensorA = new_poly_field_desc("blockResp", TYPE_INT16, 1, FORMAT_DEC);
  PF_sensorB = new_poly_field_desc("blockResp", TYPE_INT, 1, FORMAT_DEC);
  PF_sensorName = new_poly_field_desc("blockResp", TYPE_STRING, 32, FORMAT_ASCII);
  PF_blockOffset = new_poly_field_desc("blockResp", TYPE_UINT32, 1, FORMAT_HEX);
  PF_blockSize = new_poly_field_desc("blockResp", TYPE_UINT32, 1, FORMAT_DEC);
  PF_blockData = new_poly_field_desc("blockResp", TYPE_UINT8, 64, FORMAT_NONE);

  //Settomg Field Descriptors for ack
  //Settomg Field Descriptors for SetData
  poly_packet_desc_add_field(PP_SetData , PF_src , true );
  poly_packet_desc_add_field(PP_SetData , PF_dst , true );
  poly_packet_desc_add_field(PP_SetData , PF_sensorA , false );
  poly_packet_desc_add_field(PP_SetData , PF_sensorB , false );
  poly_packet_desc_add_field(PP_SetData , PF_sensorName , false );
  //Settomg Field Descriptors for GetData
  poly_packet_desc_add_field(PP_GetData , PF_src , true );
  poly_packet_desc_add_field(PP_GetData , PF_dst , true );
  poly_packet_desc_add_field(PP_GetData , PF_sensorA , false );
  poly_packet_desc_add_field(PP_GetData , PF_sensorB , false );
  poly_packet_desc_add_field(PP_GetData , PF_sensorName , false );
  //Settomg Field Descriptors for RespData
  poly_packet_desc_add_field(PP_RespData , PF_src , true );
  poly_packet_desc_add_field(PP_RespData , PF_dst , true );
  poly_packet_desc_add_field(PP_RespData , PF_sensorA , false );
  poly_packet_desc_add_field(PP_RespData , PF_sensorB , false );
  poly_packet_desc_add_field(PP_RespData , PF_sensorName , false );
  //Settomg Field Descriptors for blockReq
  poly_packet_desc_add_field(PP_blockReq , PF_src , true );
  poly_packet_desc_add_field(PP_blockReq , PF_dst , true );
  poly_packet_desc_add_field(PP_blockReq , PF_blockOffset , true );
  poly_packet_desc_add_field(PP_blockReq , PF_blockSize , true );
  //Settomg Field Descriptors for blockResp
  poly_packet_desc_add_field(PP_blockResp , PF_src , true );
  poly_packet_desc_add_field(PP_blockResp , PF_dst , true );
  poly_packet_desc_add_field(PP_blockResp , PF_blockOffset , true );
  poly_packet_desc_add_field(PP_blockResp , PF_blockSize , true );
  poly_packet_desc_add_field(PP_blockResp , PF_blockData , true );

  //Register packet descriptors with the parser
  poly_parser_register_desc(sp_PARSER, PP_ack);
  poly_parser_register_desc(sp_PARSER, PP_SetData);
  poly_parser_register_desc(sp_PARSER, PP_GetData);
  poly_parser_register_desc(sp_PARSER, PP_RespData);
  poly_parser_register_desc(sp_PARSER, PP_blockReq);
  poly_parser_register_desc(sp_PARSER, PP_blockResp);

}

/*******************************************************************************
  Packet Binding
*******************************************************************************/
//Packet binders
/**
  *@brief Binds struct to poly_parser_t
  *@param ack ptr to ack_packet_t to be bound
  *@param packet packet to bind to
  */
void ack_bind(ack_packet_t* ack, poly_packet_t* packet)
{
  ack->mPacket = packet;


}

/**
  *@brief Binds struct to poly_parser_t
  *@param setdata ptr to setdata_packet_t to be bound
  *@param packet packet to bind to
  */
void setdata_bind(setdata_packet_t* setdata, poly_packet_t* packet)
{
  setdata->mPacket = packet;

  poly_field_bind( poly_packet_get_field(packet, PF_src), (uint8_t*) &setdata->src);
  poly_field_bind( poly_packet_get_field(packet, PF_dst), (uint8_t*) &setdata->dst);
  poly_field_bind( poly_packet_get_field(packet, PF_sensorA), (uint8_t*) &setdata->sensorA);
  poly_field_bind( poly_packet_get_field(packet, PF_sensorB), (uint8_t*) &setdata->sensorB);
  poly_field_bind( poly_packet_get_field(packet, PF_sensorName), (uint8_t*) &setdata->sensorName);

}

/**
  *@brief Binds struct to poly_parser_t
  *@param getdata ptr to getdata_packet_t to be bound
  *@param packet packet to bind to
  */
void getdata_bind(getdata_packet_t* getdata, poly_packet_t* packet)
{
  getdata->mPacket = packet;

  poly_field_bind( poly_packet_get_field(packet, PF_src), (uint8_t*) &getdata->src);
  poly_field_bind( poly_packet_get_field(packet, PF_dst), (uint8_t*) &getdata->dst);
  poly_field_bind( poly_packet_get_field(packet, PF_sensorA), (uint8_t*) &getdata->sensorA);
  poly_field_bind( poly_packet_get_field(packet, PF_sensorB), (uint8_t*) &getdata->sensorB);
  poly_field_bind( poly_packet_get_field(packet, PF_sensorName), (uint8_t*) &getdata->sensorName);

}

/**
  *@brief Binds struct to poly_parser_t
  *@param respdata ptr to respdata_packet_t to be bound
  *@param packet packet to bind to
  */
void respdata_bind(respdata_packet_t* respdata, poly_packet_t* packet)
{
  respdata->mPacket = packet;

  poly_field_bind( poly_packet_get_field(packet, PF_src), (uint8_t*) &respdata->src);
  poly_field_bind( poly_packet_get_field(packet, PF_dst), (uint8_t*) &respdata->dst);
  poly_field_bind( poly_packet_get_field(packet, PF_sensorA), (uint8_t*) &respdata->sensorA);
  poly_field_bind( poly_packet_get_field(packet, PF_sensorB), (uint8_t*) &respdata->sensorB);
  poly_field_bind( poly_packet_get_field(packet, PF_sensorName), (uint8_t*) &respdata->sensorName);

}

/**
  *@brief Binds struct to poly_parser_t
  *@param blockreq ptr to blockreq_packet_t to be bound
  *@param packet packet to bind to
  */
void blockreq_bind(blockreq_packet_t* blockreq, poly_packet_t* packet)
{
  blockreq->mPacket = packet;

  poly_field_bind( poly_packet_get_field(packet, PF_src), (uint8_t*) &blockreq->src);
  poly_field_bind( poly_packet_get_field(packet, PF_dst), (uint8_t*) &blockreq->dst);
  poly_field_bind( poly_packet_get_field(packet, PF_blockOffset), (uint8_t*) &blockreq->blockOffset);
  poly_field_bind( poly_packet_get_field(packet, PF_blockSize), (uint8_t*) &blockreq->blockSize);

}

/**
  *@brief Binds struct to poly_parser_t
  *@param blockresp ptr to blockresp_packet_t to be bound
  *@param packet packet to bind to
  */
void blockresp_bind(blockresp_packet_t* blockresp, poly_packet_t* packet)
{
  blockresp->mPacket = packet;

  poly_field_bind( poly_packet_get_field(packet, PF_src), (uint8_t*) &blockresp->src);
  poly_field_bind( poly_packet_get_field(packet, PF_dst), (uint8_t*) &blockresp->dst);
  poly_field_bind( poly_packet_get_field(packet, PF_blockOffset), (uint8_t*) &blockresp->blockOffset);
  poly_field_bind( poly_packet_get_field(packet, PF_blockSize), (uint8_t*) &blockresp->blockSize);
  poly_field_bind( poly_packet_get_field(packet, PF_blockData), (uint8_t*) &blockresp->blockData);

}


/*******************************************************************************
  Weak packet handlers

  Do not modify these, just create your own without the '__weak' attribute
*******************************************************************************/
__weak uint8_t sp_ack_handler(ack_packet_t * packet)
{
  return PACKET_UNHANDLED;
}
__weak uint8_t sp_setdata_handler(setdata_packet_t * packet)
{
  return PACKET_UNHANDLED;
}
__weak uint8_t sp_getdata_handler(getdata_packet_t * packet)
{
  return PACKET_UNHANDLED;
}
__weak uint8_t sp_respdata_handler(respdata_packet_t * packet)
{
  return PACKET_UNHANDLED;
}
__weak uint8_t sp_blockreq_handler(blockreq_packet_t * packet)
{
  return PACKET_UNHANDLED;
}
__weak uint8_t sp_blockresp_handler(blockresp_packet_t * packet)
{
  return PACKET_UNHANDLED;
}
